drugstore_user:
    resource: "@DrugstoreUserBundle/Resources/config/routing/user.yml"
    prefix:   /user

drugstore_principal:
    resource: "@DrugstorePrincipalBundle/Resources/config/routing.yml"
    prefix:   /

DrugstoreUserBundle_role:
    resource: "@DrugstoreUserBundle/Resources/config/routing/role.yml"
    prefix:   /role

drugstoreUserBundle_login:
    resource: "@DrugstoreUserBundle/Resources/config/routing/login.yml"
    
