drugstore_principal_homepage:
    pattern:  /
    defaults: { _controller: DrugstorePrincipalBundle:Drugstore:index }

drugstore_medicament_add:
    pattern:  /add
    defaults: { _controller: DrugstorePrincipalBundle:Medicament:add }
    
drugstore_medicament_delete:
    pattern:  /delete
    defaults: { _controller: DrugstorePrincipalBundle:Medicament:delete }

drugstore_medicament_transfer:
    pattern:  /transfer
    defaults: { _controller: DrugstorePrincipalBundle:Medicament:transfer }

drugstore_medicament_edit:
    pattern:  /edit
    defaults: { _controller: DrugstorePrincipalBundle:Medicament:edit }

drugstore_medicament_update:
    pattern:  /edit/{id}
    defaults: { _controller: DrugstorePrincipalBundle:Medicament:update }
    
drugstore_medicament_setup_stock:
    pattern:  /stock
    defaults: { _controller: DrugstorePrincipalBundle:Medicament:setupStock }

drugstore_medicament_stock:
    pattern:  /stock/{id}
    defaults: { _controller: DrugstorePrincipalBundle:Medicament:stock }
